const BRAND  = '#166534'
const GRAY   = '#6b7280'
const LIGHT  = '#f0fdf4'
const BORDER = '#e5e7eb'
const M      = 56  // page margin

const fmtDate = (d) => d
  ? new Date(d).toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })
  : '—'

const fmtCurrency = (v) =>
  `PHP ${parseFloat(v || 0).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`

// Standard NEMSU/PRimeSys page header. Returns Y after the divider line.
function pageHeader(doc, title) {
  const W = doc.page.width - M * 2
  doc.fontSize(9).fillColor(GRAY).font('Helvetica')
     .text('NEMSU Cantilan Campus', M, M, { align: 'center', width: W })
  doc.fontSize(15).fillColor(BRAND).font('Helvetica-Bold')
     .text(title, M, M + 16, { align: 'center', width: W })
  doc.fontSize(9).fillColor(GRAY).font('Helvetica')
     .text('Procurement Management System · PRimeSys', M, M + 36, { align: 'center', width: W })
  doc.moveTo(M, M + 54).lineTo(M + W, M + 54).strokeColor(BRAND).lineWidth(1.5).stroke()
  return M + 66
}

// Standard generated-by footer at the bottom of the current page.
function pageFooter(doc) {
  const W = doc.page.width - M * 2
  const y = doc.page.height - 52
  doc.moveTo(M, y).lineTo(M + W, y).strokeColor(BORDER).lineWidth(0.5).stroke()
  doc.fontSize(8).fillColor('#9ca3af').font('Helvetica')
     .text(`Generated by PRimeSys · ${new Date().toLocaleString('en-PH')}`, M, y + 8, { align: 'center', width: W })
}

// Thin horizontal rule. Returns y unchanged (caller uses y + gap).
function hRule(doc, y, color) {
  const W = doc.page.width - M * 2
  doc.moveTo(M, y).lineTo(M + W, y).strokeColor(color || BORDER).lineWidth(0.5).stroke()
}

// Label + value field at absolute coordinates.
function metaField(doc, label, value, x, y, w) {
  doc.fontSize(8).fillColor(GRAY).font('Helvetica').text(label, x, y, { width: w || 150 })
  doc.fontSize(10).fillColor('#111827').font('Helvetica-Bold')
     .text(value || '—', x, y + 12, { width: w || 150 })
}

// Draws a signature block (line + label + name + role).
function sigBlock(doc, x, y, label, name, role) {
  doc.moveTo(x, y).lineTo(x + 190, y).strokeColor('#9ca3af').lineWidth(0.5).stroke()
  doc.fontSize(8).fillColor(GRAY).font('Helvetica').text(label, x, y + 5, { width: 190 })
  if (name) doc.fontSize(9).fillColor('#111827').font('Helvetica-Bold').text(name, x, y + 17, { width: 190 })
  if (role) doc.fontSize(8).fillColor(GRAY).font('Helvetica').text(role, x, y + 29, { width: 190 })
}

// Draws a table.
//   columns : [{ header, width, align }]
//   rows    : arrays of cell strings, OR { _group: 'label' } for group headers
//             Set row._total = true to style as a totals row.
// Returns Y after last row.
function drawTable(doc, columns, rows) {
  const x      = M
  const totalW = columns.reduce((s, c) => s + c.width, 0)
  const W      = doc.page.width - M * 2
  const ROW_H  = 22
  const HEAD_H = 24
  const PAD    = 6
  const PAGE_B = doc.page.height - 68   // stop before footer

  const drawHeader = (y) => {
    doc.rect(x, y, totalW, HEAD_H).fillColor(LIGHT).fill()
    doc.rect(x, y, totalW, HEAD_H).strokeColor(BORDER).lineWidth(0.5).stroke()
    let cx = x + PAD
    for (const col of columns) {
      doc.fontSize(8).fillColor(GRAY).font('Helvetica-Bold')
         .text(col.header, cx, y + 8, { width: col.width - PAD * 2, align: col.align || 'left', lineBreak: false })
      cx += col.width
    }
    return y + HEAD_H
  }

  let y = drawHeader(doc.y)

  for (let ri = 0; ri < rows.length; ri++) {
    const row = rows[ri]

    if (y + ROW_H > PAGE_B) {
      doc.addPage()
      y = M
      y = drawHeader(y)
    }

    // Group separator
    if (!Array.isArray(row)) {
      doc.rect(x, y, totalW, ROW_H).fillColor('#f3f4f6').fill()
      doc.rect(x, y, totalW, ROW_H).strokeColor(BORDER).lineWidth(0.3).stroke()
      doc.fontSize(8).fillColor('#374151').font('Helvetica-Bold')
         .text(row._group, x + PAD, y + 7, { width: totalW - PAD * 2, lineBreak: false })
      y += ROW_H
      continue
    }

    const isTotal = !!row._total
    const bg      = isTotal ? LIGHT : (ri % 2 === 0 ? '#ffffff' : '#f9fafb')
    doc.rect(x, y, totalW, ROW_H).fillColor(bg).fill()
    doc.rect(x, y, totalW, ROW_H).strokeColor(BORDER).lineWidth(0.3).stroke()

    let cx = x + PAD
    for (let ci = 0; ci < columns.length; ci++) {
      const col = columns[ci]
      const val = row[ci] != null ? String(row[ci]) : '—'
      doc.fontSize(9)
         .fillColor(isTotal ? BRAND : '#111827')
         .font(isTotal ? 'Helvetica-Bold' : 'Helvetica')
         .text(val, cx, y + 7, { width: col.width - PAD * 2, align: col.align || 'left', lineBreak: false })
      cx += col.width
    }
    y += ROW_H
  }

  return y
}

module.exports = { M, BRAND, GRAY, LIGHT, BORDER, fmtDate, fmtCurrency, pageHeader, pageFooter, hRule, metaField, sigBlock, drawTable }
